### ISSUE TITLE
Date/Time throws validation errors (INTAKE FORM)

### ISSUE THREAD

**Issue by souvorinkg** [DiscoTrayStudios/family-promise#13]
On the intake process page, when you put in the dates of the admittance and completion, the form throws an unclear validation error. If there needs to be a validation on this form, the error needs to be descriptive enough that a user can solve it. 
<img width="478" alt="image" src="https://github.com/DiscoTrayStudios/family-promise/assets/89923856/0d1a2a48-c6eb-4f42-b8e3-5a4f44ed986d">

**Comment by mason-t-demond** [comment]
This no longer appears to be an issue, I will close it for now, but reopen it in the case it appears again.
